Fatal error: exception Failure("illegal argument for cos, "a"")
